name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      GPG_KEY: ${{ secrets.GPG_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v2

      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Install
        run: |
          echo 'Install on ' ${GITHUB_REF##*/}
          ./mvnw install -DskipTests  -Dgpg.skip

      - name: Test
        run: |
          echo 'Start tests on ' ${GITHUB_REF##*/}
          ./mvnw test

      - name: Prepare deploy
        shell: bash
        env:
          CODESIGNING: ${{ secrets.CODESIGNING }}
        run: |
          echo 'Run deploy preparation ' ${GITHUB_REF##*/}
          ./.github/scripts/decrypt_secret.sh
          cat $HOME/secrets/my_secret.json
          openssl aes-256-cbc  -in release/codesigning.asc.enc -out release/codesigning.asc -d -k "$CODESIGNING"
          gpg --fast-import release/codesigning.asc
          rm release/codesigning.asc
          ./mvnw versions:set -DnewVersion=${GITHUB_REF#refs/tags/}

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: |
          echo 'Deploy'
          ./mvnw deploy --settings release/settings.xml
          echo 'Deploy finished successfully'