name: continuous-integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v2

      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Install
        run: |
          echo 'Install on ' ${GITHUB_REF##*/}
          ./mvnw install -DskipTests  -Dgpg.skip

      - name: Prepare deploy
        if: github.ref == 'refs/heads/master'
        run: |
          echo 'Run deploy preparation ' ${GITHUB_REF##*/}
          openssl aes-256-cbc  -in release/codesigning.asc.enc -out release/codesigning.asc -d -k ${CODESIGNING}
          gpg --fast-import release/codesigning.asc
          rm release/codesigning.asc
          ./mvnw versions:set -DnewVersion=${GITHUB_REF#refs/tags/}

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: |
          echo 'Deploy'
          ./mvnw deploy --settings release/settings.xml
          echo 'Deploy finished successfully'