name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Install
        run: |
          echo 'Install on ' ${GITHUB_REF##*/}
          ./mvnw install -DskipTests  -Dgpg.skip

      - name: Test
        run: |
          echo 'Start tests on ' ${GITHUB_REF##*/}
          ./mvnw test